#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  typeOfBusiness:
    queryParameters:
      typeOfBusiness:
        description: 'The type of business whose obligations are to be returned Must be one of: <ul><li>`self-employment`</li><li>`uk-property`</li><li>`foreign-property`</li></ul>. (If not specified) Default is to return obligations for all businesses, Must be provided if incomeSourceId is provided'
        required: false
  incomeSourceId:
    queryParameters:
      incomeSourceId:
        description: 'the unique identifier for the business whose obligations are to be returned. Must conform to the format ^X[a-zA-Z0-9]{1}IS[09]{12}$'
        example: "XAIS123456789012"
        required: false
  fromDate:
    queryParameters:
      fromDate:
        description: 'The start date of the range by which to filter obligations. Format YYYY-MM-DD. Mandatory if the “to” query parameter is supplied. If the “from” and “to” date parameters are not supplied, the date range will default to a year from today unless the status parameter is set to "O".'
        example: "2018-04-06"
        required: false
  toDate:
    queryParameters:
      toDate:
        description: 'The end date of the range by which to filter obligations, in the format YYYY-MM-DD. Mandatory if the “from” query parameter is supplied. If the “from” and “to” date parameters are not supplied, the date range will default to a year from today unless the status parameter is set to "O"'
        example: "2019-04-05"
        required: false
  status:
    queryParameters:
      status:
        description: 'Obligation status to return: Open or Fulfilled only. Omit status to retrieve all obligations.'
        required: false