is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTypeOfBusiness
  - errors.formatBusinessId
  - errors.formatFromDate
  - errors.formatToDate
  - errors.formatStatus
  - errors.missingFromDate
  - errors.missingToDate
  - errors.rangeToDateBeforeFromDate
  - errors.missingTypeOfBusiness
  - errors.ruleDateRangeInvalid
  - errors.ruleFromDateNonSupportedEOPS
  - errors.ruleInsolventTrader
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - errors.noObligationsFound
  - queryParameters.typeOfBusiness
  - queryParameters.businessId
  - queryParameters.fromDate
  - queryParameters.toDate
  - queryParameters.status
displayName: Retrieve Income Tax (Self Assessment) End of Period Statement
description: This endpoint allows a developer to retrieve the End of Period Statement obligations for a user's business income sources. The account identifier (National Insurance number) must be provided.
(annotations.sandboxData): !include scenarios/retrieve_eops_obligations_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/retrieve_eops_response.json
        examples:
          example-1:
            description: Example response
            value: !include examples/retrieve_end_of_period_obligations.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.